const puerta_de_rebatir_de_1_hoja = {
  referencias_generales: {
    A: 'Ancho total del marco',
    H: 'Altura total del marco',
    unidad_medida: 'mm',
  },
  lista_de_perfiles: [
    {
      codigo: '7727',
      cantidad: 2,
      descripcion: 'Jambas premarco',
      formula_corte: 'H+18',
      angulos_corte: '45-90',
    },
    {
      codigo: '7727',
      cantidad: 1,
      descripcion: 'Dintel premarco',
      formula_corte: 'A+40',
      angulos_corte: '45-45',
    },
    {
      codigo: '7711',
      cantidad: 2,
      descripcion: 'Jambas tapa premarco',
      formula_corte: 'H+29',
      angulos_corte: '45-90',
    },
    {
      codigo: '7711',
      cantidad: 1,
      descripcion: 'Dintel tapa premarco',
      formula_corte: 'A+58',
      angulos_corte: '45-45',
    },
    {
      codigo: '7705',
      cantidad: 2,
      descripcion: 'Jamba de marco',
      formula_corte: 'H',
      angulos_corte: '45-90',
    },
    {
      codigo: '7705',
      cantidad: 1,
      descripcion: 'Dintel de marco',
      formula_corte: 'A',
      angulos_corte: '45-45',
    },
    {
      codigo: '7726',
      cantidad: 2,
      descripcion: 'Jamba de hoja',
      formula_corte: 'H-24',
      angulos_corte: '45-90',
    },
    {
      codigo: '7726',
      cantidad: 1,
      descripcion: 'Cabezal de hoja',
      formula_corte: 'A-39',
      angulos_corte: '45-45',
    },
    {
      codigo: '7730',
      cantidad: 1,
      descripcion: 'Zócalo de hoja',
      formula_corte: 'A-191',
      angulos_corte: '90-90',
    },
    {
      codigo: '7729',
      cantidad: 1,
      descripcion: 'Travesaño de hoja',
      formula_corte: 'A-191',
      angulos_corte: '90-90',
    },
  ],
}
