const perfiles_aluminio = {
  perfiles_aluminio: [
    {
      perfil_nro: '6204',
      forma: '',
      peso_kg_m: 0.721,
      descripcion: 'Zócalo y cabezal hoja vidrio simple vent. y pta. corrediza',
    },
    {
      perfil_nro: '6206',
      forma: '',
      peso_kg_m: 0.186,
      descripcion: 'Tapa premarco curvo para clip plástico',
    },
    {
      perfil_nro: '6209',
      forma: '',
      peso_kg_m: 1.266,
      descripcion: 'Zócalo alto hoja vidrio simple puerta corrediza',
    },
    {
      perfil_nro: '6217',
      forma: '',
      peso_kg_m: 0.294,
      descripcion: 'Contravidrio recto 29 mm',
    },
    {
      perfil_nro: '6220',
      forma: '',
      peso_kg_m: 0.176,
      descripcion: 'Contravidrio recto 5 mm',
    },
    {
      perfil_nro: '6221',
      forma: '',
      peso_kg_m: 0.767,
      descripcion: 'Travesaño angosto paño fijo',
    },
    {
      perfil_nro: '6222',
      forma: '',
      peso_kg_m: 0.842,
      descripcion: 'Travesaño ancho paño fijo',
    },
    {
      perfil_nro: '6223',
      forma: '',
      peso_kg_m: 0.918,
      descripcion:
        'Encuentro central vent. de abrir de 2 hojas con cámara compensadora',
    },
    {
      perfil_nro: '6224',
      forma: '',
      peso_kg_m: 0.794,
      descripcion:
        'Encuentro central vent. de abrir de 2 hojas DC/pta. rebatir',
    },
    {
      perfil_nro: '6225',
      forma: '',
      peso_kg_m: 0.257,
      descripcion: 'Contravidrio recto 22 mm',
    },
    {
      perfil_nro: '6226',
      forma: '',
      peso_kg_m: 0.211,
      descripcion: 'Contravidrio recto 15 mm',
    },
    {
      perfil_nro: '6228',
      forma: '',
      peso_kg_m: 0.186,
      descripcion: 'Tope de mosquitero ventana y puerta corrediza',
    },
    {
      perfil_nro: '6230',
      forma: '',
      peso_kg_m: 0.213,
      descripcion: 'Contravidrio curvo 29 mm',
    },
    {
      perfil_nro: '6231',
      forma: '',
      peso_kg_m: 0.159,
      descripcion: 'Contravidrio curvo 15 mm',
    },
    {
      perfil_nro: '6232',
      forma: '',
      peso_kg_m: 0.181,
      descripcion: 'Contravidrio curvo 22 mm',
    },
    {
      perfil_nro: '6233',
      forma: '',
      peso_kg_m: 0.135,
      descripcion: 'Contravidrio curvo 8 mm',
    },
    {
      perfil_nro: '6234',
      forma: '',
      peso_kg_m: 0.888,
      descripcion: 'Hoja curva ventana de abrir con cámara compensadora',
    },
    {
      perfil_nro: '6237',
      forma: '',
      peso_kg_m: 0.176,
      descripcion: 'Contravidrio curvo 12 mm',
    },
    {
      perfil_nro: '6238',
      forma: '',
      peso_kg_m: 0.189,
      descripcion: 'Contravidrio recto 8 mm',
    },
    {
      perfil_nro: '6239',
      forma: '',
      peso_kg_m: 0.748,
      descripcion: 'Travesaño hoja vidrio simple puerta corrediza',
    },
    {
      perfil_nro: '6243',
      forma: '',
      peso_kg_m: 0.548,
      descripcion: 'Guía de cortina común',
    },
    {
      perfil_nro: '6244',
      forma: '',
      peso_kg_m: 0.913,
      descripcion: 'Guía de cortina barrio',
    },
    {
      perfil_nro: '6245',
      forma: '',
      peso_kg_m: 0.629,
      descripcion: 'Tapa cinta',
    },
    {
      perfil_nro: '6246',
      forma: '',
      peso_kg_m: 0.292,
      descripcion: 'Encuentro central 4 hojas vent. y pta. corrediza',
    },
    {
      perfil_nro: '6249',
      forma: '',
      peso_kg_m: 0.689,
      descripcion: 'Zócalo y cabezal de hoja DVH vent. y pta. corrediza',
    },
    {
      perfil_nro: '6252',
      forma: '',
      peso_kg_m: 1.237,
      descripcion: 'Zócalo alto hoja DVH puerta corrediza',
    },
    {
      perfil_nro: '6253',
      forma: '',
      peso_kg_m: 0.689,
      descripcion: 'Travesaño hoja DVH puerta corrediza',
    },
    {
      perfil_nro: '6254',
      forma: '',
      peso_kg_m: 0.302,
      descripcion: 'Bisagra tapa cinta',
    },
    {
      perfil_nro: '6255',
      forma: '',
      peso_kg_m: 0.424,
      descripcion: 'Bastidor mosquitero',
    },
    {
      perfil_nro: '6256',
      forma: '',
      peso_kg_m: 0.543,
      descripcion: 'Travesaño mosquitero',
    },
    {
      perfil_nro: '6266',
      forma: '',
      peso_kg_m: 0.383,
      descripcion: 'Bastidor vidrio repartido vent. de abrir y paño fijo',
    },
    {
      perfil_nro: '6267',
      forma: '',
      peso_kg_m: 0.383,
      descripcion: 'Bastidor vidrio repartido vent. y pta. corrediza',
    },
    {
      perfil_nro: '6268',
      forma: '',
      peso_kg_m: 0.429,
      descripcion: 'Travesaño vidrio repartido vent. y pta. corrediza',
    },
    {
      perfil_nro: '6275',
      forma: '',
      peso_kg_m: 0.88,
      descripcion: 'Hoja postigón de rebatir',
    },
    {
      perfil_nro: '6276',
      forma: '',
      peso_kg_m: 1.301,
      descripcion: 'Travesaño postigón de rebatir',
    },
    {
      perfil_nro: '6277',
      forma: '',
      peso_kg_m: 0.518,
      descripcion: 'Tablilla regulable postigón de rebatir',
    },
    {
      perfil_nro: '6278',
      forma: '',
      peso_kg_m: 0.319,
      descripcion: 'Compensador corto postigón de rebatir',
    },
    {
      perfil_nro: '6279',
      forma: '',
      peso_kg_m: 0.392,
      descripcion: 'Compensador largo postigón de rebatir',
    },
    {
      perfil_nro: '6280',
      forma: '',
      peso_kg_m: 0.367,
      descripcion: 'Soporte de compensador postigón de rebatir',
    },
    {
      perfil_nro: '6281',
      forma: '',
      peso_kg_m: 1.76,
      descripcion: 'Zócalo alto postigón de rebatir',
    },
    {
      perfil_nro: '6293',
      forma: '',
      peso_kg_m: 0.724,
      descripcion: 'Parante central externo ventana guillotina',
    },
    {
      perfil_nro: '6294',
      forma: '',
      peso_kg_m: 0.724,
      descripcion: 'Parante central interno ventana guillotina',
    },
    {
      perfil_nro: '6295',
      forma: '',
      peso_kg_m: 0.783,
      descripcion: 'Zócalo y cabezal de hoja ventana guillotina',
    },
    {
      perfil_nro: '6296',
      forma: '',
      peso_kg_m: 1.636,
      descripcion: 'Jamba de marco ventana guillotina',
    },
    {
      perfil_nro: '6297',
      forma: '',
      peso_kg_m: 1.002,
      descripcion: 'Umbral de marco ventana guillotina',
    },
    {
      perfil_nro: '6298',
      forma: '',
      peso_kg_m: 1.077,
      descripcion: 'Dintel de marco ventana guillotina',
    },
    {
      perfil_nro: '6299',
      forma: '',
      peso_kg_m: 0.119,
      descripcion: 'Tapa de resortes ventana guillotina',
    },
    {
      perfil_nro: '6900',
      forma: '',
      peso_kg_m: 0.551,
      descripcion: 'Parante lateral de hoja ventana guillotina',
    },
    {
      perfil_nro: '6901',
      forma: '',
      peso_kg_m: 0.71,
      descripcion: 'Premarco ventana guillotina/3 guías',
    },
    {
      perfil_nro: '6903',
      forma: '',
      peso_kg_m: 0.462,
      descripcion: 'Acople marco guillotina',
    },
    {
      perfil_nro: '6907',
      forma: '',
      peso_kg_m: 0.338,
      descripcion: 'Suplemento parante central corrediza corte a 45º',
    },
    {
      perfil_nro: '6908',
      forma: '',
      peso_kg_m: 0.894,
      descripcion: 'Hoja corrediza corte a 45º p/vidrio simple',
    },
    {
      perfil_nro: '6909',
      forma: '',
      peso_kg_m: 0.84,
      descripcion: 'Hoja corrediza corte a 45º DVH',
    },
    {
      perfil_nro: '6910',
      forma: '',
      peso_kg_m: 1.183,
      descripcion: 'Parante central reforzado corrediza corte a 45º',
    },
    {
      perfil_nro: '6911',
      forma: '',
      peso_kg_m: 1.126,
      descripcion: 'Parante central ref. DVH corrediza corte a 45º',
    },
    {
      perfil_nro: '7705',
      forma: '',
      peso_kg_m: 0.821,
      descripcion: 'Marco curvo para PF-VA-VB-VV-PR',
    },
    {
      perfil_nro: '7706',
      forma: '',
      peso_kg_m: 0.909,
      descripcion: 'Hoja curva ventana de abrir DC y ventana banderola',
    },
    {
      perfil_nro: '7707',
      forma: '',
      peso_kg_m: 0.772,
      descripcion:
        'Marco coplanar vent. abrir DC, vent. banderola, pta. de rebatir y vent. ventiluz',
    },
    {
      perfil_nro: '7708',
      forma: '',
      peso_kg_m: 0.902,
      descripcion: 'Hoja curva ventiluz',
    },
    {
      perfil_nro: '7709',
      forma: '',
      peso_kg_m: 0.724,
      descripcion: 'Marco ventana desplazable',
    },
    {
      perfil_nro: '7710',
      forma: '',
      peso_kg_m: 1.083,
      descripcion: 'Hoja ventana desplazable curva',
    },
    {
      perfil_nro: '7711',
      forma: '',
      peso_kg_m: 0.243,
      descripcion: 'Tapa premarco Módena',
    },
    {
      perfil_nro: '7712',
      forma: '',
      peso_kg_m: 0.284,
      descripcion: 'Perfil de acople',
    },
    {
      perfil_nro: '7713',
      forma: '',
      peso_kg_m: 1.31,
      descripcion: 'Umbral y dintel de ventana y puerta corrediza',
    },
    {
      perfil_nro: '7714',
      forma: '',
      peso_kg_m: 0.724,
      descripcion: 'Jamba de marco de ventana y puerta corrediza',
    },
    {
      perfil_nro: '7715',
      forma: '',
      peso_kg_m: 0.678,
      descripcion: 'Parante lateral hoja vidrio simple vent. y pta. corrediza',
    },
    {
      perfil_nro: '7716',
      forma: '',
      peso_kg_m: 0.71,
      descripcion: 'Parante central hoja vidrio simple vent. y pta. corrediza',
    },
    {
      perfil_nro: '7717',
      forma: '',
      peso_kg_m: 0.834,
      descripcion: 'Marco coplanar vent. de abrir con cámara compensadora',
    },
    {
      perfil_nro: '7718',
      forma: '',
      peso_kg_m: 0.774,
      descripcion: 'Perfil de acople a 90º',
    },
    {
      perfil_nro: '7719',
      forma: '',
      peso_kg_m: 0.632,
      descripcion: 'Suplemento parante central corrediza corte a 45º',
    },
    {
      perfil_nro: '7720',
      forma: '',
      peso_kg_m: 1.277,
      descripcion: 'Columna de acople reforzada',
    },
    {
      perfil_nro: '7721',
      forma: '',
      peso_kg_m: 1.866,
      descripcion: 'Umbral y dintel de marco de 3 guías vent. y pta. corrediza',
    },
    {
      perfil_nro: '7722',
      forma: '',
      peso_kg_m: 1.112,
      descripcion: 'Jamba de marco de 3 guías vent. y pta. corrediza',
    },
    {
      perfil_nro: '7723',
      forma: '',
      peso_kg_m: 0.643,
      descripcion: 'Parante lateral de hoja DVH vent. y pta. corrediza',
    },
    {
      perfil_nro: '7724',
      forma: '',
      peso_kg_m: 0.675,
      descripcion: 'Parante central hoja DVH vent. y pta. corrediza',
    },
    {
      perfil_nro: '7725',
      forma: '',
      peso_kg_m: 0.964,
      descripcion: 'Parante central con tirador hoja DVH pta. corrediza',
    },
    {
      perfil_nro: '7726',
      forma: '',
      peso_kg_m: 1.193,
      descripcion: 'Jamba y cabezal de hoja puerta de rebatir',
    },
    {
      perfil_nro: '7727',
      forma: '',
      peso_kg_m: 0.448,
      descripcion: 'Premarco Módena',
    },
    {
      perfil_nro: '7728',
      forma: '',
      peso_kg_m: 0.999,
      descripcion:
        'Parante central con tirador hoja vidrio simple pta. corrediza',
    },
    {
      perfil_nro: '7729',
      forma: '',
      peso_kg_m: 1.261,
      descripcion: 'Travesaño hoja pta. de rebatir',
    },
    {
      perfil_nro: '7730',
      forma: '',
      peso_kg_m: 1.688,
      descripcion: 'Zócalo hoja puerta de rebatir',
    },
    {
      perfil_nro: '7731',
      forma: '',
      peso_kg_m: 1.21,
      descripcion: 'Marco corrediza corte a 45º',
    },
    {
      perfil_nro: '7732',
      forma: '',
      peso_kg_m: 0.316,
      descripcion: 'Tapajunta ancho Módena',
    },
    {
      perfil_nro: '7877',
      forma: '',
      peso_kg_m: 1.185,
      descripcion: 'Jamba y cabezal de hoja puerta de rebatir hacia afuera',
    },
    {
      perfil_nro: '7878',
      forma: '',
      peso_kg_m: 0.896,
      descripcion: 'Marco puerta de rebatir coplanar para bisagra de aplica',
    },
    {
      perfil_nro: '7879',
      forma: '',
      peso_kg_m: 1.55,
      descripcion: 'Umbral corrediza con caja de agua reforzada',
    },
    {
      perfil_nro: '7880',
      forma: '',
      peso_kg_m: 1.223,
      descripcion:
        'Parante central reforzado para pta. corrediza vidrio simple',
    },
    {
      perfil_nro: '7918',
      forma: '',
      peso_kg_m: 1.195,
      descripcion: 'Parante central reforzado para pta. corrediza DVH',
    },
    {
      perfil_nro: '8008',
      forma: '',
      peso_kg_m: 1.066,
      descripcion: 'Jamba de marco de 94 mm para corrediza',
    },
    {
      perfil_nro: '8009',
      forma: '',
      peso_kg_m: 1.35,
      descripcion:
        'Marco de 94 mm para ventana de abrir con cámara compensadora',
    },
    {
      perfil_nro: '8010',
      forma: '',
      peso_kg_m: 1.291,
      descripcion: 'Marco de 94mm para ventana de abrir y paño fijo',
    },
    {
      perfil_nro: '8011',
      forma: '',
      peso_kg_m: 0.705,
      descripcion: 'Perfil de acople para marcos de 94 mm',
    },
    {
      perfil_nro: '8012',
      forma: '',
      peso_kg_m: 1.534,
      descripcion: 'Umbral y dintel de marco 94 mm para corrediza',
    },
    {
      perfil_nro: '8062',
      forma: '',
      peso_kg_m: 0.167,
      descripcion: 'Tapa premarco recto para fijar con clip plástico',
    },
    {
      perfil_nro: '8063',
      forma: '',
      peso_kg_m: 0.23,
      descripcion: 'Tapa premarco recto para fijar con tornillo',
    },
    {
      perfil_nro: '8245',
      forma: '',
      peso_kg_m: 0.374,
      descripcion: 'Adaptador DVH corrediza 90º',
    },
  ],
}
